name: Orchestration

on:
  workflow_dispatch:

jobs:

  discover:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Discovering GitLab repositories..."

  migrate:
    needs: discover
    runs-on: ubuntu-latest
    steps:
      - run: echo "Migrating repositories to GitHub..."

  convert-ci:
    needs: migrate
    uses: ./.github/workflows/gitlab-ci-converter.yml

  package-migration:
    needs: convert-ci
    uses: ./.github/workflows/package-Image-migration.yml

  metadata:
    needs: package-migration
    runs-on: ubuntu-latest
    steps:
      - run: echo "Migrating issues, labels, milestones..."

  done:
    needs: metadata
    runs-on: ubuntu-latest
    steps:
      - run: echo "Migration completed ✅"
